begin;
create table private.operation_settings(singleton boolean primary key default true check(singleton),accepts_real_data boolean not null default false,evidence_retention_days integer not null default 90 check(evidence_retention_days between 7 and 365));
insert into private.operation_settings(singleton)values(true);
alter table private.operation_settings enable row level security;revoke all on private.operation_settings from public,anon,authenticated;
create function public.get_operation_mode() returns jsonb language sql stable security definer set search_path='' as $$select jsonb_build_object('accepts_real_data',accepts_real_data,'evidence_retention_days',evidence_retention_days)from private.operation_settings where singleton;$$;
revoke all on function public.get_operation_mode()from public;grant execute on function public.get_operation_mode()to anon,authenticated;
create function public.configure_operation_mode(p_real boolean,p_days integer,p_reason text)returns void language plpgsql security definer set search_path='' as $$
begin perform private.catalogue_lock();if p_real is null or p_days is null or p_days not between 7 and 365 or p_reason is null or char_length(btrim(p_reason))not between 10 and 2000 then raise exception 'Choose mode, retention and audit reason';end if;update private.operation_settings set accepts_real_data=p_real,evidence_retention_days=p_days where singleton;insert into private.audit_events(actor_id,action,entity_id,reason,after_value)values(null,'operation_mode_configured','00000000-0000-4000-8000-000000000012',btrim(p_reason),jsonb_build_object('accepts_real_data',p_real,'evidence_retention_days',p_days));end;$$;
revoke all on function public.configure_operation_mode(boolean,integer,text)from public,anon,authenticated;grant execute on function public.configure_operation_mode(boolean,integer,text)to service_role;
create function private.check_record_mode(p_demo boolean,p_consent boolean)returns void language plpgsql security definer set search_path='' as $$
begin if p_demo is null then raise exception 'Declare demonstration or real data';end if;if not p_demo and (not coalesce(p_consent,false)or not(select accepts_real_data from private.operation_settings where singleton))then raise exception 'Real-data intake disabled or consent missing';end if;end;$$;
revoke all on function private.check_record_mode(boolean,boolean)from public,anon,authenticated,service_role;
alter table public.reviews add column is_demo boolean not null default true;
alter table private.documents add column is_demo boolean not null default true,add column expires_at timestamptz not null default(now()+interval '90 days'),add column deleted_at timestamptz;
alter table private.documents alter column object_path drop not null;
update private.documents set expires_at=created_at+interval '90 days';
create index document_expiry on private.documents(expires_at)where object_path is not null;
create or replace function public.create_property(p_input jsonb,p_acknowledged boolean default false)returns uuid language plpgsql security definer set search_path='' as $$
declare pid uuid;demo boolean:=(p_input->>'synthetic')::boolean;
begin perform private.catalogue_lock();perform private.check_record_mode(demo,(p_input->>'consent')::boolean);pid:=private.create_property_unlocked(p_input||'{"synthetic":true}'::jsonb,p_acknowledged);update public.properties set is_demo=demo where id=pid;return pid;end;$$;
create or replace function public.create_review(p_input jsonb)returns jsonb language plpgsql security definer set search_path='' as $$
declare result jsonb;demo boolean:=(p_input->>'synthetic')::boolean;target_demo boolean;
begin perform private.catalogue_lock();perform private.check_record_mode(demo,(p_input->>'consent')::boolean);select is_demo into target_demo from public.properties where id=(p_input->>'property')::uuid;if target_demo is distinct from demo then raise exception 'Review must match property demonstration status';end if;result:=private.create_review_unlocked(p_input||'{"synthetic":true}'::jsonb);if result->>'status'='created' then update public.reviews set is_demo=demo where id=(result->>'id')::uuid;end if;return result;end;$$;
create or replace function public.edit_review(p_review uuid,p_input jsonb)returns void language plpgsql security definer set search_path='' as $$
declare demo boolean;begin perform private.catalogue_lock();select r.is_demo into demo from public.reviews r join private.tenancies t on t.id=r.tenancy_id where r.id=p_review and r.status='visible' and t.user_id=auth.uid();if not found then raise exception 'Only the author can edit a visible review' using errcode='42501';end if;if demo is distinct from(p_input->>'synthetic')::boolean then raise exception 'Review demonstration status cannot be changed';end if;
-- Closing intake must not prevent existing authors from correcting their real reviews.
if not demo and not coalesce((p_input->>'consent')::boolean,false)then raise exception 'Consent required';end if;perform private.edit_review_unlocked(p_review,p_input||'{"synthetic":true}'::jsonb);end;$$;
alter function public.register_evidence_document(uuid,uuid,text,uuid,uuid,uuid)set schema private;
alter function private.register_evidence_document(uuid,uuid,text,uuid,uuid,uuid)rename to register_evidence_original;
revoke all on function private.register_evidence_original(uuid,uuid,text,uuid,uuid,uuid)from public,anon,authenticated,service_role;
create function public.register_evidence_document(p_user uuid,p_document uuid,p_extension text,p_review uuid default null,p_property uuid default null,p_landlord uuid default null,p_demo boolean default true,p_consent boolean default false)returns uuid language plpgsql security definer set search_path='' as $$
declare rid uuid;target_demo boolean;begin perform private.catalogue_lock();perform private.check_record_mode(p_demo,p_consent);
if p_review is not null then select is_demo into target_demo from public.reviews where id=p_review;elsif p_property is not null then select is_demo into target_demo from public.properties where id=p_property;else select is_demo into target_demo from public.landlords where id=p_landlord;end if;
if target_demo is distinct from p_demo then raise exception 'Evidence must match target demonstration status';end if;
rid:=private.register_evidence_original(p_user,p_document,p_extension,p_review,p_property,p_landlord);update private.documents set is_demo=p_demo,expires_at=now()+make_interval(days=>(select evidence_retention_days from private.operation_settings where singleton))where id=p_document;return rid;end;$$;
revoke all on function public.register_evidence_document(uuid,uuid,text,uuid,uuid,uuid,boolean,boolean)from public,anon,authenticated;grant execute on function public.register_evidence_document(uuid,uuid,text,uuid,uuid,uuid,boolean,boolean)to service_role;
-- Legacy JPEG endpoints remain usable for fictional fixtures only.
alter function public.register_claim_document(uuid,uuid,uuid,uuid)set schema private;
alter function private.register_claim_document(uuid,uuid,uuid,uuid)rename to register_claim_legacy;
revoke all on function private.register_claim_legacy(uuid,uuid,uuid,uuid)from public,anon,authenticated,service_role;
create function public.register_claim_document(p_user uuid,p_property uuid,p_landlord uuid,p_document uuid)returns uuid language plpgsql security definer set search_path='' as $$begin if not coalesce((select is_demo from public.properties where id=p_property),(select is_demo from public.landlords where id=p_landlord),false)then raise exception 'Use validated real-evidence registration';end if;return private.register_claim_legacy(p_user,p_property,p_landlord,p_document);end;$$;
revoke all on function public.register_claim_document(uuid,uuid,uuid,uuid)from public,anon,authenticated;grant execute on function public.register_claim_document(uuid,uuid,uuid,uuid)to service_role;
alter function public.register_verification_document(uuid,uuid,uuid)set schema private;
alter function private.register_verification_document(uuid,uuid,uuid)rename to register_verification_legacy;
revoke all on function private.register_verification_legacy(uuid,uuid,uuid)from public,anon,authenticated,service_role;
create function public.register_verification_document(p_user uuid,p_review uuid,p_document uuid)returns uuid language plpgsql security definer set search_path='' as $$begin if not coalesce((select is_demo from public.reviews where id=p_review),false)then raise exception 'Use validated real-evidence registration';end if;return private.register_verification_legacy(p_user,p_review,p_document);end;$$;
revoke all on function public.register_verification_document(uuid,uuid,uuid)from public,anon,authenticated;grant execute on function public.register_verification_document(uuid,uuid,uuid)to service_role;
create or replace function public.get_authorized_document(p_document uuid)returns text language sql stable security definer set search_path='' as $$select object_path from private.documents where id=p_document and expires_at>now()and deleted_at is null and(owner_id=auth.uid()or public.is_administrator());$$;
create function public.queue_expired_evidence(p_limit integer default 100)returns integer language plpgsql security definer set search_path='' as $$
declare count_jobs integer;begin perform private.catalogue_lock();with expired as(select id from private.documents where object_path is not null and expires_at<=now()order by expires_at,id limit least(greatest(coalesce(p_limit,100),1),1000)for update),queued as(insert into private.media_purge_queue(user_id,bucket,object_path)select d.owner_id,'rental-documents',d.object_path from private.documents d join expired e on e.id=d.id on conflict(bucket,object_path)do nothing),returning_update as(update private.documents set object_path=null,deleted_at=now()where id in(select id from expired)returning id)select count(*)into count_jobs from returning_update;return count_jobs;end;$$;
revoke all on function public.queue_expired_evidence(integer)from public,anon,authenticated;grant execute on function public.queue_expired_evidence(integer)to service_role;
create function private.check_evidence_approval(p_document uuid,p_checks jsonb)returns void language plpgsql security definer set search_path='' as $$
declare d private.documents%rowtype;begin select * into d from private.documents where id=p_document;
if not d.is_demo then if d.object_path is null or d.expires_at<=now()or p_checks->>'identity' is distinct from 'true' or p_checks->>'property' is distinct from 'true' or p_checks->>'period_or_authority' is distinct from 'true' then raise exception 'Review live evidence and complete all three checklist items';end if;end if;end;$$;
revoke all on function private.check_evidence_approval(uuid,jsonb)from public,anon,authenticated,service_role;
alter function public.decide_verification(uuid,text,text)set schema private;
alter function private.decide_verification(uuid,text,text)rename to decide_verification_original;
revoke all on function private.decide_verification_original(uuid,text,text)from public,anon,authenticated,service_role;
create function public.decide_verification(p_request uuid,p_decision text,p_reason text,p_checks jsonb default '{}'::jsonb)returns void language plpgsql security definer set search_path='' as $$
begin perform private.require_administrator();perform private.catalogue_lock();if p_decision='approved'then perform private.check_evidence_approval((select document_id from private.verification_requests where id=p_request),p_checks);end if;perform private.decide_verification_original(p_request,p_decision,p_reason);if exists(select 1 from private.verification_requests v join private.documents d on d.id=v.document_id where v.id=p_request and not d.is_demo)then insert into private.audit_events(actor_id,action,entity_id,reason,after_value)values(auth.uid(),'evidence_checklist',p_request,'Administrator recorded manual evidence checks.',p_checks);end if;end;$$;
revoke all on function public.decide_verification(uuid,text,text,jsonb)from public,anon;grant execute on function public.decide_verification(uuid,text,text,jsonb)to authenticated;
create or replace function public.decide_claim(p_claim uuid,p_decision text,p_reason text,p_checks jsonb default '{}'::jsonb)returns void language plpgsql security definer set search_path='' as $$
begin perform private.require_administrator();perform private.catalogue_lock();if p_decision='approved'then perform private.check_evidence_approval((select document_id from private.claims where id=p_claim),p_checks);end if;perform private.decide_claim_unlocked(p_claim,p_decision,p_reason);if exists(select 1 from private.claims c join private.documents d on d.id=c.document_id where c.id=p_claim and not d.is_demo)then insert into private.audit_events(actor_id,action,entity_id,reason,after_value)values(auth.uid(),'evidence_checklist',p_claim,'Administrator recorded manual evidence checks.',p_checks);end if;end;$$;
drop function public.decide_claim(uuid,text,text);
revoke all on function public.decide_claim(uuid,text,text,jsonb)from public,anon;grant execute on function public.decide_claim(uuid,text,text,jsonb)to authenticated;
create function public.operations_health()returns jsonb language plpgsql stable security definer set search_path='' as $$begin perform private.require_administrator();return jsonb_build_object('database','available','pending_media_purges',(select count(*)from private.media_purge_queue),'expired_evidence',(select count(*)from private.documents where object_path is not null and expires_at<=now()),'oldest_purge_at',(select min(created_at)from private.media_purge_queue),'mode',public.get_operation_mode());end;$$;
revoke all on function public.operations_health()from public,anon;grant execute on function public.operations_health()to authenticated;
-- Preserve historical demonstration status on every DTO, even after intake mode changes.
alter function public.get_my_reviews()set schema private;alter function private.get_my_reviews()rename to get_my_reviews_original;revoke all on function private.get_my_reviews_original()from public,anon,authenticated,service_role;
create function public.get_my_reviews()returns jsonb language sql stable security definer set search_path='' as $$select coalesce(jsonb_agg(x.value||jsonb_build_object('is_demo',r.is_demo)),'[]'::jsonb)from jsonb_array_elements(private.get_my_reviews_original())x(value)join public.reviews r on r.id=(x.value->>'id')::uuid;$$;
revoke all on function public.get_my_reviews()from public,anon;grant execute on function public.get_my_reviews()to authenticated;
alter function public.get_review_page(uuid,uuid,integer)set schema private;alter function private.get_review_page(uuid,uuid,integer)rename to get_review_page_original;revoke all on function private.get_review_page_original(uuid,uuid,integer)from public,anon,authenticated,service_role;
create function public.get_review_page(p_property uuid default null,p_landlord uuid default null,p_page integer default 1)returns jsonb language sql stable security definer set search_path='' as $$with original as(select private.get_review_page_original(p_property,p_landlord,p_page)as v)select v||jsonb_build_object('rows',(select coalesce(jsonb_agg(x.value||jsonb_build_object('is_demo',r.is_demo)order by x.ordinality),'[]'::jsonb)from jsonb_array_elements(v->'rows')with ordinality x(value,ordinality)join public.reviews r on r.id=(x.value->>'id')::uuid))from original;$$;
revoke all on function public.get_review_page(uuid,uuid,integer)from public;grant execute on function public.get_review_page(uuid,uuid,integer)to anon,authenticated;
create or replace function public.get_review_photos(p_review uuid)returns table(id uuid,alias text,role text,verified boolean,is_demo boolean)language sql stable security definer set search_path='' as $$select ph.id,profile.public_alias,'tenant'::text,public.review_is_verified(r.id),r.is_demo from private.review_photos ph join public.reviews r on r.id=ph.review_id join public.properties p on p.id=r.property_id join public.public_profiles profile on profile.id=r.profile_id where ph.review_id=p_review and ph.status='visible'and r.status='visible'and p.status='published'order by ph.created_at,ph.id;$$;
do $$declare name text;begin foreach name in array array['get_my_claims','get_admin_claims','get_my_verifications','get_admin_verifications']loop
execute format('alter function public.%I() set schema private',name);execute format('alter function private.%I() rename to %I',name,name||'_original');execute format('revoke all on function private.%I() from public,anon,authenticated,service_role',name||'_original');
execute format('create function public.%I() returns jsonb language sql stable security definer set search_path='''' as $body$ select coalesce(jsonb_agg(x.value||jsonb_build_object(''is_demo'',d.is_demo,''expires_at'',d.expires_at,''evidence_expired'',d.expires_at<=now()or d.object_path is null)order by x.ordinality),''[]''::jsonb)from jsonb_array_elements(private.%I())with ordinality x(value,ordinality)join private.documents d on d.id=(x.value->>''document_id'')::uuid $body$',name,name||'_original');
execute format('revoke all on function public.%I()from public,anon',name);execute format('grant execute on function public.%I()to authenticated',name);
end loop;end;$$;
do $$declare definition text;begin definition:=pg_get_functiondef('private.erase_account_content()'::regprocedure);if strpos(definition,'from private.documents where owner_id=old.id on conflict')=0 then raise exception 'Unexpected deletion trigger definition';end if;definition:=replace(definition,'from private.documents where owner_id=old.id on conflict','from private.documents where owner_id=old.id and object_path is not null on conflict');execute definition;end;$$;
alter function public.create_manager_profile(text,text,boolean,text)set schema private;alter function private.create_manager_profile(text,text,boolean,text)rename to create_manager_original;revoke all on function private.create_manager_original(text,text,boolean,text)from public,anon,authenticated,service_role;
create function public.create_manager_profile(p_name text,p_description text,p_acknowledged boolean,p_reason text,p_demo boolean default true,p_consent boolean default false)returns uuid language plpgsql security definer set search_path='' as $$declare mid uuid;begin perform private.require_administrator();perform private.catalogue_lock();perform private.check_record_mode(p_demo,p_consent);mid:=private.create_manager_original(p_name,p_description,p_acknowledged,p_reason);update public.landlords set is_demo=p_demo where id=mid;return mid;end;$$;
revoke all on function public.create_manager_profile(text,text,boolean,text,boolean,boolean)from public,anon;grant execute on function public.create_manager_profile(text,text,boolean,text,boolean,boolean)to authenticated;
-- A merge must not relabel fictional records as real or mix their rating populations.
alter function public.merge_properties(uuid,uuid,uuid[],uuid[],text,text,text)set schema private;alter function private.merge_properties(uuid,uuid,uuid[],uuid[],text,text,text)rename to merge_before_record_mode;revoke all on function private.merge_before_record_mode(uuid,uuid,uuid[],uuid[],text,text,text)from public,anon,authenticated,service_role;
create function public.merge_properties(p_source uuid,p_target uuid,p_archive uuid[],p_revoke uuid[],p_history text,p_details text,p_reason text)returns void language plpgsql security definer set search_path='' as $$begin perform private.require_administrator();perform private.catalogue_lock();if(select is_demo from public.properties where id=p_source)is distinct from(select is_demo from public.properties where id=p_target)then raise exception 'Cannot merge demonstration and real profiles';end if;perform private.merge_before_record_mode(p_source,p_target,p_archive,p_revoke,p_history,p_details,p_reason);end;$$;
revoke all on function public.merge_properties(uuid,uuid,uuid[],uuid[],text,text,text)from public,anon;grant execute on function public.merge_properties(uuid,uuid,uuid[],uuid[],text,text,text)to authenticated;
alter table private.review_photos add column cleanup_queued_at timestamptz;
alter table private.property_photos add column cleanup_queued_at timestamptz;
create function public.queue_retired_photos(p_limit integer default 100)returns integer language plpgsql security definer set search_path='' as $$
declare total integer:=0;amount integer;begin perform private.catalogue_lock();
with retired as(select ph.id from private.review_photos ph join public.reviews r on r.id=ph.review_id where ph.cleanup_queued_at is null and(ph.status in('deleted','removed')or r.status='deleted')order by ph.id limit least(greatest(coalesce(p_limit,100),1),1000)),queued as(insert into private.media_purge_queue(user_id,bucket,object_path)select t.user_id,'review-photos',ph.object_path from private.review_photos ph join retired e on e.id=ph.id join public.reviews r on r.id=ph.review_id join private.tenancies t on t.id=r.tenancy_id on conflict(bucket,object_path)do nothing),marked as(update private.review_photos set cleanup_queued_at=now()where id in(select id from retired)returning id)select count(*)into amount from marked;total:=total+amount;
with retired as(select id from private.property_photos where cleanup_queued_at is null and status in('deleted','removed')order by id limit least(greatest(coalesce(p_limit,100),1),1000)),queued as(insert into private.media_purge_queue(user_id,bucket,object_path)select owner_id,'review-photos',object_path from private.property_photos ph join retired e on e.id=ph.id on conflict(bucket,object_path)do nothing),marked as(update private.property_photos set cleanup_queued_at=now()where id in(select id from retired)returning id)select count(*)into amount from marked;return total+amount;end;$$;
revoke all on function public.queue_retired_photos(integer)from public,anon,authenticated;grant execute on function public.queue_retired_photos(integer)to service_role;
alter function public.maintain_association(uuid,uuid,date,date,uuid,text)set schema private;alter function private.maintain_association(uuid,uuid,date,date,uuid,text)rename to maintain_association_before_mode;revoke all on function private.maintain_association_before_mode(uuid,uuid,date,date,uuid,text)from public,anon,authenticated,service_role;
create function public.maintain_association(p_property uuid,p_landlord uuid,p_start date,p_end date,p_replace uuid,p_reason text)returns void language plpgsql security definer set search_path='' as $$begin perform private.require_administrator();perform private.catalogue_lock();if(select is_demo from public.properties where id=p_property)is distinct from(select is_demo from public.landlords where id=p_landlord)then raise exception 'Property and manager must share demonstration status';end if;perform private.maintain_association_before_mode(p_property,p_landlord,p_start,p_end,p_replace,p_reason);end;$$;
revoke all on function public.maintain_association(uuid,uuid,date,date,uuid,text)from public,anon;grant execute on function public.maintain_association(uuid,uuid,date,date,uuid,text)to authenticated;
commit;
