begin;
create table private.contact_preferences(user_id uuid primary key references auth.users(id) on delete cascade,enabled boolean not null default false);
create table private.conversations(id uuid primary key default gen_random_uuid(),property_id uuid not null references public.properties(id),tenant_id uuid not null references auth.users(id) on delete cascade,representative_id uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),unique(property_id,tenant_id,representative_id),check(tenant_id<>representative_id));
create table private.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references private.conversations(id) on delete cascade,sender_id uuid not null references auth.users(id) on delete cascade,body text not null check(char_length(btrim(body)) between 1 and 2000),hidden boolean not null default false,created_at timestamptz not null default now());
create index messages_thread_date on private.messages(conversation_id,created_at desc,id);
create index messages_sender_date on private.messages(sender_id,created_at desc);
create table private.conversation_blocks(conversation_id uuid references private.conversations(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,primary key(conversation_id,user_id));
create table private.message_reports(id uuid primary key default gen_random_uuid(),message_id uuid not null references private.messages(id) on delete cascade,reporter_id uuid not null references auth.users(id) on delete cascade,reason text not null check(char_length(btrim(reason)) between 10 and 2000),status text not null default 'pending' check(status in('pending','kept','removed')),decision_reason text,created_at timestamptz not null default now(),unique(message_id,reporter_id));
alter table private.contact_preferences enable row level security;alter table private.conversations enable row level security;alter table private.messages enable row level security;alter table private.conversation_blocks enable row level security;alter table private.message_reports enable row level security;
revoke all on private.contact_preferences,private.conversations,private.messages,private.conversation_blocks,private.message_reports from public,anon,authenticated;
create function private.contact_eligible(p_user uuid,p_property uuid) returns boolean language sql stable security definer set search_path='' as $$
select exists(select 1 from public.properties p join private.claims c on c.property_id=p.id or c.landlord_id in(select a.landlord_id from public.management_associations a where a.property_id=p.id and a.active and exists(select 1 from public.landlords l where l.id=a.landlord_id and l.status='published') and a.start_date<=(now() at time zone 'Asia/Kolkata')::date and (a.end_date is null or a.end_date>(now() at time zone 'Asia/Kolkata')::date)) join private.contact_preferences pref on pref.user_id=c.user_id and pref.enabled where p.id=p_property and p.status='published' and c.user_id=p_user and c.status='approved');$$;
create function public.set_contact_preference(p_enabled boolean) returns void language plpgsql security definer set search_path='' as $$
begin if auth.uid() is null or p_enabled is null then raise exception 'Sign in required' using errcode='42501';end if;perform private.catalogue_lock();insert into private.contact_preferences values(auth.uid(),p_enabled) on conflict(user_id) do update set enabled=excluded.enabled;end;$$;
create function public.get_contact_preference() returns boolean language sql stable security definer set search_path='' as $$select coalesce((select enabled from private.contact_preferences where user_id=auth.uid()),false);$$;
create function public.get_contactable_representatives(p_property uuid) returns jsonb language sql stable security definer set search_path='' as $$
select coalesce(jsonb_agg(jsonb_build_object('profile_id',a.public_profile_id,'alias',p.public_alias)),'[]'::jsonb) from private.accounts a join public.public_profiles p on p.id=a.public_profile_id where auth.uid() is not null and a.user_id<>auth.uid() and private.contact_eligible(a.user_id,p_property);$$;
create function public.start_conversation(p_property uuid,p_profile uuid,p_consent boolean) returns uuid language plpgsql security definer set search_path='' as $$
declare rep uuid;cid uuid;
begin perform private.catalogue_lock();select user_id into rep from private.accounts where public_profile_id=p_profile;
if auth.uid() is null or not coalesce(p_consent,false) or rep is null or rep=auth.uid() or not private.contact_eligible(rep,p_property) or private.user_owns_property(auth.uid(),p_property) then raise exception 'Contact unavailable or consent required' using errcode='42501';end if;
select id into cid from private.conversations where property_id=p_property and tenant_id=auth.uid() and representative_id=rep;if cid is not null then return cid;end if;
if (select count(*) from private.conversations where tenant_id=auth.uid() and created_at>now()-interval '1 hour')>=5 then raise exception 'Please wait before starting more conversations';end if;
insert into private.conversations(property_id,tenant_id,representative_id)values(p_property,auth.uid(),rep)returning id into cid;return cid;end;$$;
create function public.get_my_conversations() returns jsonb language sql stable security definer set search_path='' as $$
select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc,x.id),'[]'::jsonb)from(select c.id,c.property_id,p.name as property_name,profile.public_alias as other_alias,c.tenant_id=auth.uid() as is_tenant,exists(select 1 from private.conversation_blocks b where b.conversation_id=c.id and b.user_id=auth.uid()) as blocked_by_me,exists(select 1 from private.conversation_blocks b where b.conversation_id=c.id) as blocked,private.contact_eligible(c.representative_id,c.property_id) as contact_enabled,c.created_at from private.conversations c join public.properties p on p.id=c.property_id join private.accounts a on a.user_id=case when c.tenant_id=auth.uid() then c.representative_id else c.tenant_id end join public.public_profiles profile on profile.id=a.public_profile_id where auth.uid() in(c.tenant_id,c.representative_id) order by c.created_at desc,c.id limit 100)x;$$;
create function public.get_conversation_messages(p_conversation uuid,p_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin if not exists(select 1 from private.conversations where id=p_conversation and auth.uid() in(tenant_id,representative_id)) then raise exception 'Conversation unavailable' using errcode='42501';end if;
return(select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at,x.id),'[]'::jsonb)from(select m.id,case when m.hidden then '[Removed following moderation]' else m.body end as body,m.sender_id=auth.uid() as mine,m.hidden,m.created_at from private.messages m where m.conversation_id=p_conversation order by m.created_at desc,m.id desc limit 50 offset (least(greatest(coalesce(p_page,1),1),1000)-1)*50)x);end;$$;
create function public.send_message(p_conversation uuid,p_body text) returns uuid language plpgsql security definer set search_path='' as $$
declare c private.conversations%rowtype;mid uuid;recipient uuid;
begin perform private.catalogue_lock();select * into c from private.conversations where id=p_conversation;
if c.id is null or auth.uid() is null or auth.uid() not in(c.tenant_id,c.representative_id) or not private.contact_eligible(c.representative_id,c.property_id) or exists(select 1 from private.conversation_blocks where conversation_id=c.id) then raise exception 'Messaging unavailable' using errcode='42501';end if;
if p_body is null or char_length(btrim(p_body)) not between 1 and 2000 then raise exception 'Use 1–2000 characters';end if;
if (select count(*) from private.messages where sender_id=auth.uid() and created_at>now()-interval '1 minute')>=10 or (select count(*) from private.messages where sender_id=auth.uid() and created_at>now()-interval '1 day')>=100 then raise exception 'Message limit reached; please wait';end if;
insert into private.messages(conversation_id,sender_id,body)values(c.id,auth.uid(),btrim(p_body))returning id into mid;recipient:=case when auth.uid()=c.tenant_id then c.representative_id else c.tenant_id end;
insert into private.notifications(user_id,kind,message,href)values(recipient,'message','You received a private message.','/messages/'||c.id::text);return mid;end;$$;
create function public.set_conversation_block(p_conversation uuid,p_blocked boolean) returns void language plpgsql security definer set search_path='' as $$
begin perform private.catalogue_lock();if p_blocked is null or not exists(select 1 from private.conversations where id=p_conversation and auth.uid() in(tenant_id,representative_id))then raise exception 'Conversation unavailable' using errcode='42501';end if;
if p_blocked then insert into private.conversation_blocks values(p_conversation,auth.uid())on conflict do nothing;else delete from private.conversation_blocks where conversation_id=p_conversation and user_id=auth.uid();end if;end;$$;
create function public.report_message(p_message uuid,p_reason text) returns void language plpgsql security definer set search_path='' as $$
begin if not exists(select 1 from private.messages m join private.conversations c on c.id=m.conversation_id where m.id=p_message and auth.uid() in(c.tenant_id,c.representative_id) and m.sender_id<>auth.uid() and not m.hidden)then raise exception 'Message unavailable' using errcode='42501';end if;
if p_reason is null or char_length(btrim(p_reason)) not between 10 and 2000 then raise exception 'Use a reason of 10–2000 characters';end if;
insert into private.message_reports(message_id,reporter_id,reason)values(p_message,auth.uid(),btrim(p_reason))on conflict(message_id,reporter_id)do nothing;end;$$;
create function public.get_admin_message_reports() returns jsonb language plpgsql stable security definer set search_path='' as $$
begin perform private.require_administrator();return(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb)from(select r.id,r.reason,r.status,r.decision_reason,m.body from private.message_reports r join private.messages m on m.id=r.message_id order by r.created_at desc,r.id limit 100)x);end;$$;
create function public.decide_message_report(p_report uuid,p_decision text,p_reason text) returns void language plpgsql security definer set search_path='' as $$
declare r private.message_reports%rowtype;
begin perform private.require_administrator();perform private.catalogue_lock();select * into r from private.message_reports where id=p_report for update;
if r.id is null or r.status<>'pending' or p_decision is null or p_decision not in('kept','removed') or p_reason is null or char_length(btrim(p_reason)) not between 10 and 2000 then raise exception 'Choose a pending report and decision reason';end if;
update private.message_reports set status=p_decision,decision_reason=btrim(p_reason) where id=r.id;if p_decision='removed' then update private.messages set hidden=true where id=r.message_id;end if;
insert into private.audit_events(actor_id,action,entity_id,reason)values(auth.uid(),'message_report_'||p_decision,r.id,btrim(p_reason));
insert into private.notifications(user_id,kind,message,href)values(r.reporter_id,'message_report','Your private message report was decided: '||p_decision||'.','/account/notifications');end;$$;
revoke all on function private.contact_eligible(uuid,uuid) from public,anon,authenticated,service_role;
revoke all on function public.set_contact_preference(boolean),public.get_contact_preference(),public.get_contactable_representatives(uuid),public.start_conversation(uuid,uuid,boolean),public.get_my_conversations(),public.get_conversation_messages(uuid,integer),public.send_message(uuid,text),public.set_conversation_block(uuid,boolean),public.report_message(uuid,text),public.get_admin_message_reports(),public.decide_message_report(uuid,text,text) from public,anon;
grant execute on function public.set_contact_preference(boolean),public.get_contact_preference(),public.get_contactable_representatives(uuid),public.start_conversation(uuid,uuid,boolean),public.get_my_conversations(),public.get_conversation_messages(uuid,integer),public.send_message(uuid,text),public.set_conversation_block(uuid,boolean),public.report_message(uuid,text),public.get_admin_message_reports(),public.decide_message_report(uuid,text,text) to authenticated;

create table public.property_locations(property_id uuid primary key references public.properties(id) on delete cascade,latitude numeric not null check(latitude between 6 and 38),longitude numeric not null check(longitude between 68 and 98),precision text not null check(precision in('approximate','exact')),updated_at timestamptz not null default now());
alter table public.property_locations enable row level security;revoke all on public.property_locations from public,anon,authenticated;grant select on public.property_locations to anon,authenticated;
create policy published_locations on public.property_locations for select to anon,authenticated using(exists(select 1 from public.properties where id=property_id and status='published'));
create function public.set_property_location(p_property uuid,p_latitude numeric,p_longitude numeric,p_precision text,p_reason text)returns void language plpgsql security definer set search_path='' as $$
begin perform private.require_administrator();perform private.catalogue_lock();if not exists(select 1 from public.properties where id=p_property and status='published')or p_reason is null or char_length(btrim(p_reason))not between 10 and 2000 then raise exception 'Choose a property and audit reason';end if;
if p_latitude is null and p_longitude is null then delete from public.property_locations where property_id=p_property;else if p_latitude is null or p_longitude is null then raise exception 'Enter both coordinates';end if;insert into public.property_locations values(p_property,p_latitude,p_longitude,p_precision,now())on conflict(property_id)do update set latitude=excluded.latitude,longitude=excluded.longitude,precision=excluded.precision,updated_at=now();end if;
insert into private.audit_events(actor_id,action,entity_id,reason)values(auth.uid(),'property_location_updated',p_property,btrim(p_reason));end;$$;
revoke all on function public.set_property_location(uuid,numeric,numeric,text,text)from public,anon;grant execute on function public.set_property_location(uuid,numeric,numeric,text,text)to authenticated;
commit;
